export const TopCollection_data = [
  {
    id: "1",
    img1: "/BlogImages/4.jpg",
    img2: "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    currImg: 1,
    name: "Black Dress",
    price: " 500",
    Category: "Best Seller",
    cartState1: true,
  },
  {
    id: "2",
    img1: "/BlogImages/4.jpg",
    img2: "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    currImg: 1,
    name: "Black Dress",
    price: " 500",
    Category: "Best Seller",
    cartState1: true,
  },
  {
    id: "3",
    img1: "/BlogImages/4.jpg",
    img2: "/BlogImages/2.jpg",
    currImg: 1,
    name: "Black Dress",
    price: " 500",
    Category: "Best Seller",
    cartState1: true,
  },
  {
    id: "4",
    img1: "/BlogImages/4.jpg",
    img2: "/BlogImages/2.jpg",
    currImg: 1,
    name: "Black Dress",
    price: " 500",
    Category: "Featured",
    cartState1: true,
  },
  {
    id: "5",
    img1: "/BlogImages/4.jpg",
    img2: "/BlogImages/2.jpg",
    currImg: 1,
    name: "Black Dress",
    price: " 500",
    Category: "Featured",
    cartState1: true,
  },
  {
    id: "6",
    img1: "/BlogImages/4.jpg",
    img2: "/BlogImages/2.jpg",
    currImg: 1,
    name: "Black Dress",
    price: " 500",
    Category: "Featured",
    cartState1: true,
  },
  {
    id: "7",
    img1: "/BlogImages/4.jpg",
    img2: "/BlogImages/2.jpg",
    currImg: 1,
    name: "Black Dress",
    price: " 500",
    Category: "Recommended",
    cartState1: true,
  },
  {
    id: "8",
    img1: "/BlogImages/4.jpg",
    img2: "/BlogImages/2.jpg",
    currImg: 1,
    name: "Black Dress",
    price: " 500",
    Category: "Recommended",
    cartState1: true,
  },
];
